# Generated by Django 5.0.6 on 2024-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=40)),
                ('teacher_email', models.EmailField(max_length=30)),
            ],
        ),
    ]
